name: Quarto Publish
on:
  push:
    branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-4-${{ hashFiles('**/*.Rmd', '**/*.qmd') }}
          restore-keys: ${{ runner.os }}-r-4-
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev
        
      - name: Install R packages needed for rendering
        run: |
          Rscript -e 'if (!requireNamespace("rmarkdown", quietly = TRUE)) install.packages("rmarkdown", repos="https://cloud.r-project.org")'
          Rscript -e 'if (!requireNamespace("knitr", quietly = TRUE)) install.packages("knitr", repos="https://cloud.r-project.org")'
          Rscript -e 'if (!requireNamespace("tidyverse", quietly = TRUE)) install.packages("tidyverse", repos="https://cloud.r-project.org")'
          Rscript -e 'if (!requireNamespace("leaflet", quietly = TRUE)) install.packages("leaflet", repos="https://cloud.r-project.org")'
          Rscript -e 'if (!requireNamespace("htmltools", quietly = TRUE)) install.packages("htmltools", repos="https://cloud.r-project.org")'

          
      - uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Render site
        run: quarto render
        
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site